name: The T-Shirt Kids
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05829
title: The T-Shirt Kids
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a22546'
    - '#00579e'
    - '#010101'
    - '#c68583'
    - '#c4e8f7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
