name: The T-Shirt Kids
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16275
title: The T-Shirt Kids
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feab16'
    - '#005aa1'
    - '#ffffff'
    - '#b85169'
    - '#6086bf'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
