name: The T-Shirt Kids
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29012788319960237
title: The T-Shirt Kids
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cd1350'
    - '#23a0de'
    - '#8c9116'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
